



-- JOIN OU INNER JOIN = RELACIONA TABELAS QUE TENHAM INFORMAÇÕES IGUAIS. SE NÃO  TIVEREM INFORMAÇÕES IGUAIS, NÃO RELACIONA.
-- LEFT JOIN = PRIORIZA A PRIMEIRA TABELA: T1
-- RIGHT JOIN = PRIORIZA A SEGUNDA TABEL: T2
-- FULL JOIN = TRAZ TUDO AS TABELAST1 E T2
