SELECT 

	FIRSTNAME		AS 'PRIMEIRO NOME'
	,MIDDLENAME		AS 'NOME DO MEIO'
	,LASTNAME		AS 'ÚLTIMO NOME'
	,ADDRESSLINE1	AS ENDERECO
	,ADDRESSLINE2	AS ENDERECO2

FROM DimCustomer

WHERE ADDRESSLINE2 IS NOT NULL
AND MIDDLENAME IS NOT NULL
--WHERE ADDRESSLINE2 IS NULL