SELECT *

FROM DimEmployee

-- WHERE FirstName LIKE 'AND%' --COMEÇA COM AND
-- WHERE FirstName LIKE '%NA' --TERMINA COM NA
-- WHERE FirstName LIKE '%JA%' -- EM ALGUM LUGAR NO MEIO DO NOME
WHERE FirstName LIKE '%JA_' -- O ANDERLINE PODE SER QUALQUER CARACTER

ORDER BY FirstName